Resolve credit card issue
nato000/cloudcash pull request #19
Opened 2022-01-30 04:14 UTC by nato000

![image](https://user-images.githubusercontent.com/64704016/151686287-63e46cce-00c4-4b27-b006-f9ba2713a464.png)

⬇

![image](https://user-images.githubusercontent.com/64704016/151686270-f805ae8c-0619-4edb-aaa8-146cec6b9e5b.png)

2022-01-30 20:04 UTC, frontend-sensei commented on css/components/card/card.css
> +  width: calc(var(--width) * var(--quantity) + 25px);
Why do you set width here?

2022-01-30 20:05 UTC, frontend-sensei commented on css/components/card/card.css
> +  top: calc(0px + var(--height) * 0.5);
For what "0px"?

2022-01-30 20:06 UTC, frontend-sensei commented on css/components/card/card.css
> +  top: calc(0px + var(--height) * 0.5);
Duplicated props. (Line 67)

2022-01-30 21:49 UTC, nato000 commented on css/components/card/card.css
> +  top: calc(0px + var(--height) * 0.5);
idk mb bug

2022-01-30 21:49 UTC, nato000 commented on css/components/card/card.css
> +  top: calc(0px + var(--height) * 0.5);
that's not mine))

2022-01-30 22:07 UTC, nato000 commented
![image](https://user-images.githubusercontent.com/64704016/151719841-be6b60ea-4501-4fe6-936d-612f7613cc71.png)

⬇

![image](https://user-images.githubusercontent.com/64704016/151719873-d11f92c0-a9e5-4536-a7af-ad055ef83930.png)

2022-01-31 10:43 UTC, frontend-sensei requested changes

2022-01-31 10:43 UTC, frontend-sensei commented on css/components/card/card.css
>    --quantity: 2;
Redundant var

2022-02-01 10:18 UTC, merged